travis:
  secure:
    BINSTAR_TOKEN: kIP8lk4mjRqlhN/BzB5tD8vU5DJPDcfn6MgMmXACexRINvIAK6opG/+p/3LGt2wl8dg898n6PwtsKfSVhCRw1NnKb6TKaWbehXmCLreAooUqNeKeeOIpqazMNBKm3zvFnJYugp/v9uqjMCeUhxibpsIJenUlmLqetmCi4c67iiqVRN4PNHr1+m+clhleeULcs/rKQvw7EvK5H9/nivJ3Ndily9u6Z+wq6/G/7OqC7/LwklXDaFm0fDxgY+SwZOuDzTYPKFMMD5ItJqueiVWfDHvpt/uYcX3KvCENjaMOESSqShIRpi2mF53OU/2lk0d4+U88e8nu2leYkQgunModAnLNE7crGmAN850OKGluctxMUsTIeL+hFVdrYieTTF05xYZ7Fx3+heh9iGGDpN/Nn77PQw8p8Z3qXzwePDhfo/B9NDcUJBG1uobwBqF2Ux1FxC2/XpVZl6koLHrTJYK28+YBNQuhTU30GRILtSiA0SpbBo4fK427h99ug61w1A2XEUftEK1eRT6FKIJXIzszbR/crPoHHKFPLwpthbkEgN3mPe6uECIVZwLOqaTbFpRRYTF6rXDUzDJjjAz4U85u7Xb4E4jbIgegu75oXCbtuLMRhP2jH0wQIh03Hdj5uu5qzvaXYZfRrBWAI4az4RrisLgrvyFeSrw3V+pau6/9NWI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
